name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: preinstall
      run: sudo apt install build-essential git clang lldb clang-tidy clang-tools cppcheck
    - name: create directroies
      run: make create
    - name: clean workspace
      run: make clean
      # 5.05 Support
    - name: make 5.05 loader
      run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_505 make
    - name: make 5.05 elf
      run: MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_505 make
