name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: preinstall
      uses: ryankurte/action-apt@v0.1.0
      with:
        # architectures to pass to dpkg --add-architecture
        architectures: # optional
        # apt packages to install
        packages: build-essential git clang lldb clang-tidy clang-tools cppcheck
    - name: create directroies
      run: make create
    - name: clean workspace
      run: make clean
      # 5.05 Support
    - name: make 5.05 loader
      run: cd loader; MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_505 make
    - name: make 5.05 elf
      run: MIRA_PLATFORM=MIRA_PLATFORM_ORBIS_BSD_505 make
